### ISSUE TITLE
[Developer Experience]: Add DevContainer to make contributor experience smoother 

### ISSUE THREAD

**Issue by LadyKerr** [TechIsHiring/techishiring-website#120]
## Improve Developer Experience

**Please describe your Developer Experience Issue.**
Sometimes it's hard for first time contributors to get started with submitting contributions - because setting up the project locally can be a hassel. I propose adding a devcontainer to the project to customize the experience and make contributing even easier. 

**Describe the solution you'd like**
I will add a `.devcontainer` folder to the project which will include a `.devcontainer.json` file that will take care of installing dependencies, and opening up the environment for users. The container will also include a forwarded port and will automatically open up the `_app.tsx` file and a browser window for the user to start exploring the code. 

**Teachability, Documentation, Adoption, Migration Strategy**
I will update the readme to include an `open in codespaces` badge and also instructions on how to use the Codespaces option.

**Comment by LadyKerr** [comment]
I have the container setup and ready to go, let me know what you think about this suggestion. I also have a[ blog post ](https://github.blog/2023-03-06-how-to-automate-your-dev-environment-with-dev-containers-and-github-codespaces/)that was already written about how I did it. Let me know if you'd like me to actually add the container to this project.

**Comment by chadstewart** [comment]
> I have the container setup and ready to go, let me know what you think about this suggestion. I also have a[ blog post ](https://github.blog/2023-03-06-how-to-automate-your-dev-environment-with-dev-containers-and-github-codespaces/)that was already written about how I did it. Let me know if you'd like me to actually add the container to this project.

Hey @LadyKerr, thanks so much for this! I read through the blog post and yeah, absolutely! I'd love for you to contribute this! Ironically, I started using Codespaces a bit myself because @blackgirlbytes had made mention that you were interested in doing a blog post on it. I'm not particularly good at it but I've really enjoyed using them!

The only change I'd request is instead of opening up the _app.tsx file automatically, that it runs storybook automatically. I haven't been very good about doing it but part of the work flow I'd love to promote is building Front-End components in isolation, either new Front-End components or updating existing ones, before adding it to the project. I think having the codespace consistently open Storybook would help promote that work flow!

Thanks so very much for this and really look forward to the contribution!

**Comment by chadstewart** [comment]
Hey @LadyKerr. Just wanted to reach out and how this was coming along. Is there anything I can assist with by any chance?

**Comment by LadyKerr** [comment]
Hey @chadstewart I submitted a PR today for this!
Apologies for delay, been busy writing a talk for upcoming conference.
