### ISSUE TITLE
Feat: Add a Style Guide to the project

### ISSUE THREAD

**Issue by chadstewart** [TechIsHiring/techishiring-website#73]
## Feature Request

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I have an issue when [...]

So currently the only way to know what style would be preferred for contributions is if you go into the code and look. Without that context, it's much harder for contributors to come in and make meaningful changes without having to throw away a lot of work.

An example of this is this discussion thread: https://github.com/TechIsHiring/techishiring-website/pull/72#discussion_r1114500318

**Describe the solution you'd like**
A clear and concise description of what you want to happen. Add any considered drawbacks.

Add a Style Guide to the project. This will likely need to be added in Contributing.md and possibly the README.

As I've personally never written an official Style Guide, any help would be very much appreciated in doing this. I'll also do some research on other projects to see how they handled this issue.

What I'd need help with is:

1. What are the important things to capture
2. Where should I mention these things
3. What can be automated vs. what will I need to look out for in PRs?

**Describe alternatives you've considered**

Currently there are no alternatives but I'd like to leave this space for adding them as research is done and advice is potentially given.

**Teachability, Documentation, Adoption, Migration Strategy**
If you can, explain how users will be able to use this and possibly write out a version in the docs.
Maybe a screenshot or design?

When talking on contributors, try to find the intersection between making the process of making a contribution as painless as possible while also maintaining a project as painless as possible.

**Comment by chadstewart** [comment]
Hey @royanger @TAKANOME-DEV, any ideas?

**Comment by royanger** [comment]
Looking at Issue 72, my take isn't that we should worry about a style guide. Two general things are happening in that Issue:

1. At least one arbitrary addition of style changes (the breakpoints that were later removed) to the project.
2. The use of Chakra UI for some of the work.

For point 1, I don't think we need style guide. There was no need to add those breakpoints, and the correct approach was for those to be reverted to the very sensible Tailwind defaults. If someone submits that kind of stuff it should be called out and move on. Unfortunately a style guide won't stop this kind of stuff -- just limit some of the more obvious instances. 

Point 2 is, I think, firmly addressed in [Issue 60](https://github.com/TechIsHiring/techishiring-website/issues/60). The mixing of Tailwind and Chakra will cause issues like this and is, in general, probably a bad idea. Removing it and streamlining things it probably the far better approach. Once done there is no need for a style guide -- we're just using Tailwind and if someone adds Charka/MUI/Bootstrap/etc to a PR that PR should be rejected until that stuff is removed and replaced by Tailwind.

Generally I lean to the 'let's not make up rules/docs/tooling changes/etc' just because someone submitted something that they shouldn't have. This just makes it harder for for everyone. More things to write, update and maintain as a project maintainer and way more things to read, learn and keep in mind when making any changes. 

More importantly, you already have Storybook installed and setup for this. That should be the style guide for the project. That's where I would look to see how things are done.

**Comment by TAKANOME-DEV** [comment]
:100: agree with @royanger. 

I never wrote or see a style guide in an open source project so far. As Roy said, addressing [issue 60](https://github.com/TechIsHiring/techishiring-website/issues/60) should be enough to let contributors know which framework we're using for the styles.

For the PR `72`, I would recommend avoiding as much as possible adding custom screen sizes and colors unless needed.

**Comment by chadstewart** [comment]
That makes sense. I still need to spend the time to explore the Tailwind UI libraries you suggested, I just haven't gotten around to that.

I'll close this issue and if another issue comes up that's similar to this one, we can reopen this or just reference it in another issue.
