### ISSUE TITLE
Upgrade to Next 13 & TypeScript 5

### ISSUE THREAD

**Issue by royanger** [TechIsHiring/techishiring-website#74]
## Feature Request

**Describe the solution you'd like**
Upgrade to Next 13 and migrate to new features in that release.

**Describe alternatives you've considered**
No reasonable alternatives.

**Comment by royanger** [comment]
If you have no opposition to this @chadstewart, I can start work on this.

**Comment by chadstewart** [comment]
> If you have no opposition to this @chadstewart, I can start work on this.

Hey @royanger. So I wanted to hold off on this initially because I was worried about the amount of effort it would take to migrate over to Next.js 13 and if we'd get a lot of benefit from it. I hadn't looked too much into it after initial release since I was just trying to get things to a point they can be launched.

That said, I'd say go ahead and start this though and submit a PR for this upgrade. Try your best to aim for not being too disruptive in the upgrade if you can. We can slowly migrate to Next.js 13 features once the upgrade itself is completed.

**Comment by royanger** [comment]
Sounds good. I think the 'disruptive' will get handled in the PR. Go ahead and assign this to me, please.

**Comment by chadstewart** [comment]
Hey @royanger, how's the update coming along?

**Comment by chadstewart** [comment]
Gonna take over this issue and also update to TypeScript 5 since we're doing the updating work either way.
